<?php

?>
<h1>Bellingham Cohousing Units and People</h1>

<ul class="p">
    <li>Any user can 
        <ul>
            <li>view units and their resident history</li>
            <li>view people who have lived in cohousing and the units they occupied</li>
        </ul></li>
    
    <li>Admin users can
        <ul>
            <li>add new residents who move in</li>
            <li>change the name of a resident (e.g. for marriage)</li>
            <li>change the unit of a resident</li>
            <li>change the guest limit for a unit in the reservation system</li>
        </ul></li>
</ul>
