<?php

//~ Template for unit-detail.php
// variables:
//  $unit - Unit to be displayed

/* @var $unit Unit */
?>

<h3>
    <form>
    <fieldset>
        <div class="field">
            <label>ID:</label>
            <input type="text" name="dummy" hidden/>
            <?php echo Utils::escape($unit->getId()); ?>
        </div>
        <div class="field">
            <label>Address:</label>
            <input type="text" name="dummy" value="<?php echo Utils::escape($unit->getAddress()); ?>" hidden/>
            <?php echo Utils::escape($unit->getAddress()); ?>
        </div>
        <div class="field">
            <label>Building:</label>
            <input type="text" name="dummy" hidden/>
            <?php echo Utils::escape($unit->getBuildingId()); ?>
        </div>
        <div class="field">
            <label>Type:</label>
            <input type="text" name="dummy" hidden/>
            <?php echo Utils::escape($unit->getType()); ?>
        </div>
        <div class="field">
            <label>Guest Limit:</label>
            <input type="text" name="dummy" hidden/>
            <?php echo Utils::escape($unit->getGuestLimit()); ?>
        </div>
    </fieldset>
    </form>
</h3>

<table class="detail">
    <tr>
        <th>Actions</th>
        <td>
            <div class="actions">
                <a href="<?php 
                echo Utils::createLink('edit-unit', array('id' => $unit->getId())); 
                ?>"><img src="img/action/edit.png" alt="" title="Edit it." class="icon" /></a>
            </div>
        </td>
    </tr>
</table>

<p>
    <?php 
    $backLink = Utils::createLink('unit-list', array()); 
    ?>
    <a href="<?php 
    echo $backLink; 
    ?>"><img src="img/action/back.png" alt="" title="Back to the list." class="icon"/></a>&nbsp;
    <a href="<?php 
    echo $backLink; 
    ?>">To the list</a>
</p>

<div id="change-status-dialog">
    <form id="change-status-form" method="post">
        <fieldset>
            <div class="field">
                <label>Comment:</label>
                <textarea name="comment" cols="1" rows="1"></textarea>
            </div>
        </fieldset>
    </form>
</div>
